project_id = "qdwihdmhlebiyvdezoyl"

[auth]
enabled = true

[auth.email]
enable_confirmations = true

[functions.admin-login]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.admin-action]
verify_jwt = false
